management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "info,health"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

security:
  clientId: 790559581357-unedu44hsccmr8atn35m3hmktio2tqqp.apps.googleusercontent.com
  allowed-origins:
    - "http://localhost:3000"
    - "http://load-balancer-gameflix-backend-754529149.ap-northeast-2.elb.amazonaws.com"
    - "http://www.gameflix.link"
    - "https://www.gameflix.link"
    - "https://opgg-hackthon.github.io"

infrastructure:
  gog:
    baseUrl: https://www.gog.com
  blizzard:
    baseUrl: https://kr.api.blizzard.com
  steam:
    baseUrl: http://api.steampowered.com
    apiKey: 5A056E8523B769BF45CFF8FA144F4451
  igdb:
    baseUrl: https://api.igdb.com/v4
    token: 2ukmci1s2036phlfog3e4119uvnopg
    clientId: dkm9apjokbggtp29y6gp19ch27k1eu
spring:
  jpa:
    open-in-view: false