management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "info,health"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

security:
  clientId: 790559581357-unedu44hsccmr8atn35m3hmktio2tqqp.apps.googleusercontent.com

infrastructure:
  gog:
    baseUrl: https://www.gog.com
  blizzard:
    baseUrl: https://kr.api.blizzard.com
  steam:
    baseUrl: http://api.steampowered.com
    apiKey: 11BF521429D930FA056F734AE22A27ED
  igdb:
    baseUrl: https://api.igdb.com/v4
    token: 2ukmci1s2036phlfog3e4119uvnopg
    clientId: dkm9apjokbggtp29y6gp19ch27k1eu
spring:
  jpa:
    open-in-view: false